### ISSUE TITLE
Play downloaded file

### ISSUE THREAD

**Issue by anisalibegic** [X-SLAYER/YouTube-MP3-APP#1]
Is it possible to download the MP3 file into Downloads folder and play it with Music application?

**Comment by X-SLAYER** [comment]
> Is it possible to download the MP3 file into Downloads folder and play it with Music application?
yes its possible just check this https://flutter.dev/docs/cookbook/persistence/reading-writing-files

**Comment by anisalibegic** [comment]
> > Is it possible to download the MP3 file into Downloads folder and play it with Music application?
> > yes its possible just check this https://flutter.dev/docs/cookbook/persistence/reading-writing-files

I already tried this and it was not working... Can you please make a demo or something?

**Comment by X-SLAYER** [comment]
> > > Is it possible to download the MP3 file into Downloads folder and play it with Music application?
> > > yes its possible just check this https://flutter.dev/docs/cookbook/persistence/reading-writing-files
> 
> I already tried this and it was not working... Can you please make a demo or something?

oke i will try to do that

**Comment by grandpa-guru** [comment]
> > > > Is it possible to download the MP3 file into Downloads folder and play it with Music application?
> > > > yes its possible just check this https://flutter.dev/docs/cookbook/persistence/reading-writing-files
> > 
> > 
> > I already tried this and it was not working... Can you please make a demo or something?
> 
> oke i will try to do that

Any success?

**Comment by anisalibegic** [comment]
> 
> 
> > > > Is it possible to download the MP3 file into Downloads folder and play it with Music application?
> > > > yes its possible just check this https://flutter.dev/docs/cookbook/persistence/reading-writing-files
> > 
> > 
> > I already tried this and it was not working... Can you please make a demo or something?
> 
> oke i will try to do that

Any success?
